# Generated by Django 3.1.5 on 2021-04-09 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20210409_0636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_spec4',
            field=models.CharField(blank='True', default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_spec5',
            field=models.CharField(blank='True', default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_spec6',
            field=models.CharField(blank='True', default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_spec7',
            field=models.CharField(blank='True', default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_spec8',
            field=models.CharField(blank='True', default='', max_length=50),
        ),
    ]
