# Generated by Django 3.1.5 on 2021-04-09 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20210409_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_spec3',
            field=models.CharField(blank='True', default='', max_length=100),
        ),
    ]
