# Generated by Django 3.1.5 on 2021-04-09 08:23

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20210409_1138'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('last', models.CharField(max_length=50)),
                ('product_name', models.CharField(max_length=50)),
                ('email', models.CharField(default='', max_length=70)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('msg', models.CharField(default='', max_length=500)),
            ],
        ),
        migrations.DeleteModel(
            name='employee',
        ),
    ]
