# Generated by Django 3.1.5 on 2021-04-10 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20210409_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='product_spec10',
            field=models.CharField(blank='True', default='', max_length=100),
        ),
        migrations.AddField(
            model_name='products',
            name='product_spec9',
            field=models.CharField(blank='True', default='', max_length=100),
        ),
    ]
